# LootLink item/npc NAME + QUALITY generator (DEV ONLY).
# Bakes inline names so the addon shows correct names instantly (no GetItemInfo
# async flicker), works offline, and can search by name. Sourced from the
# CMaNGOS item_template (name+Quality) and creature_template (npc name).
# Only items/npcs that appear in the loot tables are included, to keep size down.
param(
    [string] $Sql     = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\tools\cmangos\tbcdb.sql",
    [string] $OutFile = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\Data\LootLinkItems.lua"
)
if (-not (Test-Path $Sql) -and (Test-Path "$Sql.gz")) {
    $in = [System.IO.File]::OpenRead("$Sql.gz")
    $gz = New-Object System.IO.Compression.GzipStream($in, [System.IO.Compression.CompressionMode]::Decompress)
    $out = [System.IO.File]::Create($Sql); $gz.CopyTo($out); $out.Close(); $gz.Close(); $in.Close()
}
if (-not (Test-Path $Sql)) { throw "SQL not found: $Sql" }

$rxIdId  = [regex]"\((\d+),(\d+),"                                                  # entry, item
$rxItem  = [regex]"\((\d+),\d+,\d+,-?\d+,'((?:[^'\\]|\\.)*)',\d+,(\d+),"             # entry, name, quality
$rxNpc   = [regex]"\((\d+),'((?:[^'\\]|\\.)*)'"                                      # entry, name

function LuaStr([string]$s) {
    $s = [regex]::Replace($s, '\\(.)', '$1')          # undo SQL escaping (\' -> ', \\ -> \)
    return $s.Replace('\', '\\').Replace('"', '\"')   # escape for a Lua "double-quoted" string
}

# 1) Collect item IDs + creature entries referenced by the loot tables.
$wantItems = New-Object 'System.Collections.Generic.HashSet[int]'
$wantNpcs  = New-Object 'System.Collections.Generic.HashSet[int]'
foreach ($table in @('creature_loot_template','reference_loot_template')) {
    $needle = "INSERT INTO ``$table`` VALUES"
    $isCreature = ($table -eq 'creature_loot_template')
    foreach ($line in [System.IO.File]::ReadLines($Sql)) {
        if (-not $line.StartsWith($needle)) { continue }
        foreach ($m in $rxIdId.Matches($line)) {
            $it = [int]$m.Groups[2].Value; if ($it -gt 0) { [void]$wantItems.Add($it) }
            if ($isCreature) { [void]$wantNpcs.Add([int]$m.Groups[1].Value) }
        }
    }
}
Write-Host ("Referenced: {0} items, {1} npcs" -f $wantItems.Count, $wantNpcs.Count)

# 2) item_template -> name + quality (only wanted items).
$itemName = @{}; $itemQual = @{}
$needle = "INSERT INTO ``item_template`` VALUES"
foreach ($line in [System.IO.File]::ReadLines($Sql)) {
    if (-not $line.StartsWith($needle)) { continue }
    foreach ($m in $rxItem.Matches($line)) {
        $id = [int]$m.Groups[1].Value
        if ($wantItems.Contains($id)) { $itemName[$id] = LuaStr $m.Groups[2].Value; $itemQual[$id] = [int]$m.Groups[3].Value }
    }
}
# 3) creature_template -> npc name (only wanted npcs).
$npcName = @{}
$needle = "INSERT INTO ``creature_template`` VALUES"
foreach ($line in [System.IO.File]::ReadLines($Sql)) {
    if (-not $line.StartsWith($needle)) { continue }
    foreach ($m in $rxNpc.Matches($line)) {
        $id = [int]$m.Groups[1].Value
        if ($wantNpcs.Contains($id)) { $npcName[$id] = LuaStr $m.Groups[2].Value }
    }
}
Write-Host ("Resolved: {0} item names, {1} npc names" -f $itemName.Count, $npcName.Count)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by tools/generate-items.ps1 — do not edit.")
[void]$sb.AppendLine("-- Inline names + quality (CMaNGOS item_template / creature_template).")
[void]$sb.AppendLine("LootLinkItemName = {")
foreach ($id in ($itemName.Keys | Sort-Object)) { [void]$sb.AppendLine(("[{0}]=`"{1}`"," -f $id, $itemName[$id])) }
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("LootLinkItemQuality = {")
foreach ($id in ($itemQual.Keys | Sort-Object)) { [void]$sb.AppendLine(("[{0}]={1}," -f $id, $itemQual[$id])) }
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("LootLinkNpcName = {")
foreach ($id in ($npcName.Keys | Sort-Object)) { [void]$sb.AppendLine(("[{0}]=`"{1}`"," -f $id, $npcName[$id])) }
[void]$sb.AppendLine("}")

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ("Wrote {0}  ({1:N0} KB)" -f $OutFile, ((Get-Item $OutFile).Length / 1KB))
