# LootLink quest-item flag generator (DEV ONLY).
# Emits Data/LootLinkQuestItems.lua:  LootLinkQuestItem = { [itemId]=1, ... }
# Source: CMaNGOS item_template, class == 12 (Quest). Limited to items LootLink knows
# about (present in LootLinkItemName) so the table stays small and only covers drops
# we can actually display.
param(
    [string] $Sql      = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\tools\cmangos\tbcdb.sql",
    [string] $ItemsLua  = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\Data\LootLinkItems.lua",
    [string] $Out       = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\Data\LootLinkQuestItems.lua",
    [switch] $ProbeOnly
)
# known item ids = keys already in LootLinkItemName
$known=@{}
$rxId=[regex]"^\[(\d+)\]="
$inItems=$false
foreach($line in [System.IO.File]::ReadLines($ItemsLua)){
  if($line.StartsWith("LootLinkItemName")){ $inItems=$true; continue }
  if($inItems -and $line.StartsWith("}")){ break }
  if($inItems){ $m=$rxId.Match($line); if($m.Success){ $known[[int]$m.Groups[1].Value]=$true } }
}

function SplitTuples([string]$s){$o=New-Object System.Collections.Generic.List[string];$d=0;$q=$false;$st=-1
 for($i=0;$i -lt $s.Length;$i++){$c=$s[$i]
  if($q){if($c -eq '\'){$i++}elseif($c -eq "'"){$q=$false};continue}
  if($c -eq "'"){$q=$true}elseif($c -eq '('){if($d -eq 0){$st=$i+1};$d++}elseif($c -eq ')'){$d--;if($d -eq 0){$o.Add($s.Substring($st,$i-$st))}}}
 return $o}
function SplitFields([string]$s){$f=New-Object System.Collections.Generic.List[string];$q=$false;$st=0
 for($i=0;$i -lt $s.Length;$i++){$c=$s[$i]
  if($q){if($c -eq '\'){$i++}elseif($c -eq "'"){$q=$false}}elseif($c -eq "'"){$q=$true}elseif($c -eq ','){$f.Add($s.Substring($st,$i-$st));$st=$i+1}}
 $f.Add($s.Substring($st));return $f}

$questIds=New-Object 'System.Collections.Generic.HashSet[int]'
$sample=New-Object System.Collections.Generic.List[string]
$totalQuest=0
$needle="INSERT INTO ``item_template`` VALUES"
foreach($line in [System.IO.File]::ReadLines($Sql)){
  if(-not $line.StartsWith($needle)){continue}
  foreach($t in SplitTuples $line.Substring($needle.Length)){
    $f=SplitFields $t
    if($f.Count -lt 5){continue}
    $cls=0; if(-not [int]::TryParse($f[1].Trim(),[ref]$cls)){continue}
    if($cls -ne 12){continue}
    $totalQuest++
    $id=0; if(-not [int]::TryParse($f[0].Trim(),[ref]$id)){continue}
    if($known.ContainsKey($id)){
      [void]$questIds.Add($id)
      if($sample.Count -lt 12){ [void]$sample.Add(("{0}={1}" -f $id, $f[4].Trim().Trim("'"))) }
    }
  }
}
Write-Host ("class==12 quest items total: {0}; intersecting LootLink items: {1}" -f $totalQuest,$questIds.Count)
Write-Host ("sample: " + ($sample -join ' | '))
if($ProbeOnly){ return }

$sb=[System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by tools/generate-questitems.ps1 — do not edit.")
[void]$sb.AppendLine("-- Item ids that are Quest-class (item_template.class==12). Used to flag quest drops.")
[void]$sb.AppendLine("LootLinkQuestItem = {")
foreach($id in ($questIds | Sort-Object)){ [void]$sb.AppendLine(("[{0}]=1," -f $id)) }
[void]$sb.AppendLine("}")
[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ("Wrote {0}: {1} quest items, {2:N0} KB" -f $Out,$questIds.Count,((Get-Item $Out).Length/1KB))
