# LootLink Wowhead-% generator (DEV ONLY).
# Inverts Questie's bundled wowheadData (item -> {npc -> %}) into a whole-game
# npc -> {item -> %} lookup map, baked into our own file (no Questie runtime dep).
# This powers /loot everywhere AND the "(WH x%)" overlay shown in /fullloot.
param(
    [string] $QuestieDB = "E:\World of Warcraft\_anniversary_\Interface\AddOns\Questie\Database",
    [string] $OutFile   = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\Data\LootLinkWowhead.lua"
)
$drop = Join-Path $QuestieDB "DropTables\data\tbcItemDrops.lua"
if (-not (Test-Path $drop)) { throw "Questie drop data not found: $drop" }

$npc = @{}                # npcId -> hashtable(item -> pct)
$inBlock = $false; $cur = 0
foreach ($line in [System.IO.File]::ReadLines($drop)) {
    if (-not $inBlock) {
        if ($line.Contains('wowheadData = [[')) { $inBlock = $true }
        continue
    }
    if ($line.Contains('cmangosData = [['))   { break }
    if ($line -match '^\s+\[(\d+)\] = ([\d.]+),') {
        if ($cur -ne 0) {
            $n = [int]$Matches[1]
            if (-not $npc.ContainsKey($n)) { $npc[$n] = @{} }
            $npc[$n][$cur] = [double]$Matches[2]
        }
    }
    elseif ($line -match '^\s*\[(\d+)\] = \{') { $cur = [int]$Matches[1] }
}

$outDir = Split-Path $OutFile
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force $outDir | Out-Null }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by tools/generate-wowhead.ps1 — do not edit by hand.")
[void]$sb.AppendLine("-- Source: Questie's bundled Wowhead TBC drop data (quest-relevant items only).")
[void]$sb.AppendLine("-- Format: LootLinkWowhead[npcID] = { [itemID] = dropPct, ... }  (Wowhead-observed %).")
[void]$sb.AppendLine("LootLinkWowhead = LootLinkWowhead or {}")
[void]$sb.AppendLine("local w = LootLinkWowhead")
[void]$sb.AppendLine("")

$nNpc = 0; $nRows = 0
foreach ($n in ($npc.Keys | Sort-Object)) {
    $items = $npc[$n]
    if ($items.Count -eq 0) { continue }
    $nNpc++
    $parts = foreach ($kv in ($items.GetEnumerator() | Sort-Object Value -Descending)) {
        $nRows++
        "[{0}]={1}" -f [int]$kv.Key, ([math]::Round($kv.Value, 2))
    }
    [void]$sb.AppendLine(("w[{0}]={{{1}}}" -f $n, ($parts -join ",")))
}

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ("Wrote {0} NPCs / {1} item rows -> {2}" -f $nNpc, $nRows, $OutFile)
Write-Host ("Output size: {0:N0} KB" -f ((Get-Item $OutFile).Length / 1KB))
