# LootLink data generator (DEV ONLY — not loaded by the addon).
#
# Reads Questie's bundled, Wowhead-sourced TBC drop data and NPC database,
# inverts "item -> {npc -> rate}" into "npc -> {item -> rate}", and emits a
# compact Lua data file for one or more zones.
#
# Item name / quality / icon are intentionally NOT shipped — LootLink resolves
# those at runtime via GetItemInfo(), so the data file stays tiny.
#
# Usage:  pwsh tools/generate.ps1            (defaults to Elwynn Forest, zone 12)
#         pwsh tools/generate.ps1 -ZoneId 1  (Dun Morogh), etc.

param(
    [int]    $ZoneId    = 12,
    [string] $ZoneName  = "Elwynn Forest",
    [string] $QuestieDB = "E:\World of Warcraft\_anniversary_\Interface\AddOns\Questie\Database",
    [string] $OutFile   = "E:\World of Warcraft\_anniversary_\Interface\AddOns\LootLink\Data\LootLinkData.lua"
)

$npcFile  = Join-Path $QuestieDB "TBC\tbcNpcDB.lua"
$dropFile = Join-Path $QuestieDB "DropTables\data\tbcItemDrops.lua"

if (-not (Test-Path $npcFile))  { throw "NPC DB not found: $npcFile" }
if (-not (Test-Path $dropFile)) { throw "Drop DB not found: $dropFile" }

# --- 1. Collect NPCs that spawn (or path) in the target zone -----------------
# Any NPC present in zone N has the substring "[N]={" on its one-line entry
# (it appears as a key in the spawns/waypoints sub-tables, which use no spaces).
$zoneKey = "[{0}]=`{{" -f $ZoneId      # e.g. "[12]={"
$npcName = @{}                          # npcId -> name
foreach ($line in [System.IO.File]::ReadLines($npcFile)) {
    if ($line.Length -lt 6 -or $line[0] -ne '[') { continue }
    if (-not ($line -match '^\[(\d+)\] = \{')) { continue }
    $id = [int]$Matches[1]
    if ($line.Contains($zoneKey)) {
        $name = ''
        if ($line -match "\{'([^']*)'") { $name = $Matches[1] }
        $npcName[$id] = $name
    }
}
Write-Host ("Zone {0} ({1}): {2} NPCs present" -f $ZoneId, $ZoneName, $npcName.Count)

# --- 2. Parse the Wowhead drop block, keeping only our zone's NPCs -----------
$npcItems = @{}              # npcId -> (itemId -> rate)
$inBlock  = $false
$curItem  = 0
foreach ($line in [System.IO.File]::ReadLines($dropFile)) {
    if (-not $inBlock) {
        if ($line.Contains('wowheadData = [[')) { $inBlock = $true }
        continue
    }
    if ($line.Contains('cmangosData = [['))   { break }   # past the Wowhead block

    # NPC rate line:  "        [6] = 11.074,"  (numeric value)
    if ($line -match '^\s+\[(\d+)\] = ([\d.]+),') {
        if ($curItem -ne 0) {
            $npc = [int]$Matches[1]
            if ($npcName.ContainsKey($npc)) {
                if (-not $npcItems.ContainsKey($npc)) { $npcItems[$npc] = @{} }
                $npcItems[$npc][$curItem] = [double]$Matches[2]
            }
        }
    }
    # Item header line: "    [159] = { -- Refreshing Spring Water"  (value is "{")
    elseif ($line -match '^\s*\[(\d+)\] = \{') {
        $curItem = [int]$Matches[1]
    }
}

# --- 3. Merge with any existing output, then emit ----------------------------
# Entries are one line each:  data[ID] = {{item,rate},...} -- Name
# so re-running for a new zone unions cleanly by NPC id without losing others.
$outDir = Split-Path $OutFile
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force $outDir | Out-Null }

$entries = [ordered]@{}   # npcId(string) -> full "data[..] = {..} -- Name" line
$zones   = [System.Collections.Generic.List[string]]::new()

if (Test-Path $OutFile) {
    foreach ($line in [System.IO.File]::ReadLines($OutFile)) {
        if ($line -match '^-- Zones:\s*(.+)$') {
            foreach ($z in ($Matches[1] -split ',\s*')) { if ($z) { [void]$zones.Add($z.Trim()) } }
        }
        elseif ($line -match '^data\[(\d+)\]') {
            $entries[$Matches[1]] = $line
        }
    }
}
if (-not $zones.Contains($ZoneName)) { [void]$zones.Add($ZoneName) }

# Build/refresh this zone's entries.
$withLoot = 0
foreach ($npc in ($npcItems.Keys | Sort-Object)) {
    $items = $npcItems[$npc]
    if ($items.Count -eq 0) { continue }
    $withLoot++
    $pairs = $items.GetEnumerator() | Sort-Object Value -Descending
    $name  = ($npcName[$npc] -replace '--', '-').TrimEnd()
    $parts = foreach ($p in $pairs) { "{{{0},{1}}}" -f $p.Key, ([math]::Round($p.Value, 2)) }
    $entries["$npc"] = "data[{0}] = {{{1}}} -- {2}" -f $npc, ($parts -join ","), $name
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by tools/generate.ps1 — do not edit by hand.")
[void]$sb.AppendLine("-- Source: Questie bundled Wowhead TBC drop data. Rates are drop % (Wowhead-observed).")
[void]$sb.AppendLine("-- Format: data[npcID] = { {itemID, dropRate}, ... } sorted by rate desc.")
[void]$sb.AppendLine(("-- Zones: {0}" -f ($zones -join ", ")))
[void]$sb.AppendLine("LootLinkData = LootLinkData or {}")
[void]$sb.AppendLine("local data = LootLinkData")
[void]$sb.AppendLine("")
foreach ($id in ($entries.Keys | Sort-Object { [int]$_ })) {
    [void]$sb.AppendLine($entries[$id])
}

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ("Added/updated {0} NPCs for {1}." -f $withLoot, $ZoneName)
Write-Host ("Total NPCs in file: {0} across zones: {1}" -f $entries.Count, ($zones -join ", "))
Write-Host ("Output size: {0:N1} KB" -f ((Get-Item $OutFile).Length / 1KB))
