blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/SokratisV/LootLink/discussions
    about: For usage questions and general discussion (not bugs).
