# WhatItDrops instance-boss table generator (DEV ONLY).
#
# Emits Data/WhatItDropsBosses.lua:  WhatItDropsInstanceBoss = { [mapId] = { npcId, ... }, ... }
#
# The Classic/Anniversary client has no Encounter Journal (EJ_*) API and CMaNGOS has
# no encounter table, so "boss" is derived heuristically from the world DB:
#   an NPC that spawns exactly ONCE in an instance map AND drops rare+ (quality >= 3)
#   loot, OR is Rank 3 (world/raid boss).  This isolates dungeon bosses cleanly; the
#   only gap is script-SUMMONED bosses (Ragnaros, Majordomo, Nefarian) which have no
#   spawn row and so can't be mapped to their instance from this data.
param(
    [string] $Sql      = "E:\World of Warcraft\_anniversary_\Interface\AddOns\WhatItDrops\tools\cmangos\tbcdb.sql",
    [string] $CodexDB  = "E:\World of Warcraft\_anniversary_\Interface\AddOns\WhatItDrops\tools\lootcodex\LootCodexDB.lua",
    [string] $Out      = "E:\World of Warcraft\_anniversary_\Interface\AddOns\WhatItDrops\Data\WhatItDropsBosses.lua"
)
$CONTINENTS = @{ 0=$true; 1=$true; 530=$true }   # not instances

# --- 1) creature spawns: (entry,map) -> count -------------------------------
$rxSpawn=[regex]"\((\d+),(\d+),(\d+),"
$spawnCount=@{}
$needleC="INSERT INTO ``creature`` VALUES"
foreach($line in [System.IO.File]::ReadLines($Sql)){
  if(-not $line.StartsWith($needleC)){continue}
  foreach($m in $rxSpawn.Matches($line)){
    $id=[int]$m.Groups[2].Value; $mid=[int]$m.Groups[3].Value
    if($CONTINENTS.ContainsKey($mid)){continue}
    $k="$id`:$mid"; if($spawnCount.ContainsKey($k)){$spawnCount[$k]++}else{$spawnCount[$k]=1}
  }
}

# --- 2) creature_template: entry -> Rank (field index 31) -------------------
function SplitTuples([string]$s){$o=New-Object System.Collections.Generic.List[string];$d=0;$q=$false;$st=-1
 for($i=0;$i -lt $s.Length;$i++){$c=$s[$i]
  if($q){if($c -eq '\'){$i++}elseif($c -eq "'"){$q=$false};continue}
  if($c -eq "'"){$q=$true}elseif($c -eq '('){if($d -eq 0){$st=$i+1};$d++}elseif($c -eq ')'){$d--;if($d -eq 0){$o.Add($s.Substring($st,$i-$st))}}}
 return $o}
function SplitFields([string]$s){$f=New-Object System.Collections.Generic.List[string];$q=$false;$st=0
 for($i=0;$i -lt $s.Length;$i++){$c=$s[$i]
  if($q){if($c -eq '\'){$i++}elseif($c -eq "'"){$q=$false}}elseif($c -eq "'"){$q=$true}elseif($c -eq ','){$f.Add($s.Substring($st,$i-$st));$st=$i+1}}
 $f.Add($s.Substring($st));return $f}
$rank=@{}
$needleT="INSERT INTO ``creature_template`` VALUES"
foreach($line in [System.IO.File]::ReadLines($Sql)){
  if(-not $line.StartsWith($needleT)){continue}
  foreach($t in SplitTuples $line.Substring($needleT.Length)){
    $cm=$t.IndexOf(','); if($cm -lt 1){continue}; $e=0; if(-not [int]::TryParse($t.Substring(0,$cm),[ref]$e)){continue}
    $f=SplitFields $t; if($f.Count -gt 31){$r=0;[void][int]::TryParse($f[31].Trim(),[ref]$r);$rank[$e]=$r}
  }
}

# --- 3) LootCodex: npc -> max drop quality (and which npcs are known) -------
function SplitTop([string]$s){$f=New-Object System.Collections.Generic.List[string];$d=0;$q=$false;$st=0
 for($i=0;$i -lt $s.Length;$i++){$c=$s[$i]
  if($q){if($c -eq '\'){$i++}elseif($c -eq '"'){$q=$false}}elseif($c -eq '"'){$q=$true}
  elseif($c -eq '{'){$d++}elseif($c -eq '}'){$d--}elseif($c -eq ',' -and $d -eq 0){$f.Add($s.Substring($st,$i-$st));$st=$i+1}}
 $f.Add($s.Substring($st));return $f}
$rxHeader=[regex]"^\s*\[(\d+)\]\s*=\s*\{\s*--\s*(.*)$"; $rxRow=[regex]"^\s*\{(.+)\},?\s*$"
$npcMaxQ=@{}; $known=@{}; $cur=0
foreach($line in [System.IO.File]::ReadLines($CodexDB)){
  $h=$rxHeader.Match($line); if($h.Success){$cur=[int]$h.Groups[1].Value;$known[$cur]=$true;continue}
  if($cur -le 0){continue}; $rm=$rxRow.Match($line); if(-not $rm.Success){continue}
  $f=SplitTop $rm.Groups[1].Value; if($f.Count -lt 4){continue}
  $q=0;[void][int]::TryParse($f[3].Trim(),[ref]$q); if(-not $npcMaxQ.ContainsKey($cur) -or $q -gt $npcMaxQ[$cur]){$npcMaxQ[$cur]=$q}
}

# --- 4) apply rule ----------------------------------------------------------
$byMap=@{}   # mapId -> HashSet[int]
foreach($k in $spawnCount.Keys){
  $parts=$k.Split(':'); $id=[int]$parts[0]; $mid=[int]$parts[1]
  if(-not $known.ContainsKey($id)){continue}            # must have a known loot table to be worth showing
  $q=if($npcMaxQ.ContainsKey($id)){$npcMaxQ[$id]}else{0}
  $r=if($rank.ContainsKey($id)){$rank[$id]}else{0}
  if(($spawnCount[$k] -eq 1 -and $q -ge 3) -or $r -eq 3){
    if(-not $byMap.ContainsKey($mid)){$byMap[$mid]=New-Object 'System.Collections.Generic.HashSet[int]'}
    [void]$byMap[$mid].Add($id)
  }
}

# --- 5) write Lua -----------------------------------------------------------
$sb=[System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by tools/generate-bosses.ps1 — do not edit.")
[void]$sb.AppendLine("-- Instance map id -> boss NPC ids. Heuristic: single-spawn rare+ dropper, or Rank 3.")
[void]$sb.AppendLine("WhatItDropsInstanceBoss = {")
$totalMaps=0;$totalBosses=0
foreach($mid in ($byMap.Keys | Sort-Object)){
  $ids=@($byMap[$mid] | Sort-Object)
  if($ids.Count -eq 0){continue}
  $totalMaps++; $totalBosses+=$ids.Count
  [void]$sb.AppendLine(("[{0}]={{{1}}}," -f $mid, ($ids -join ",")))
}
[void]$sb.AppendLine("}")
[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ("Wrote {0}: {1} instance maps, {2} bosses, {3:N0} KB" -f $Out,$totalMaps,$totalBosses,((Get-Item $Out).Length/1KB))
