"""WhatItDrops retail data generator (DEV ONLY).

Source: TrinityCore TDB world database (GPL v3), https://github.com/TrinityCore/TrinityCore/releases
  e.g. TDB_full_1210.26091_2026_09_09.7z  ->  TDB_full_world_*.sql

Emits one LoadOnDemand pack, WhatItDrops_Retail, in the same flat layout the classic
packs use:  d[npc] = { specificCount, itemID, pct, itemID, pct, ... }  sorted by rate,
plus WhatItDropsNpcName[npc]. Item names/quality are NOT baked: the TDB hotfix dump
holds only a handful of items, so the addon asks the client at runtime.

Run:  python generate-retail-from-tdb.py <TDB_full_world.sql> <AddOns dir>
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tdbparse as t  # noqa: E402

MAX_ROWS = 400      # a table past this is data corruption, not loot (cf. the Don Carlos bug)
ITEM = 0            # creature_loot_template.ItemType: 0 item, 1 currency, 2 reference


def group_chances(rows):
    """Resolve TrinityCore's 'Chance = 0 inside a group' into real percentages.

    Rows of one GroupId are mutually exclusive: explicit chances are taken as given
    and the entries left at 0 share whatever is left of 100% equally.
    """
    by_group = collections.defaultdict(list)
    for r in rows:
        by_group[r["GroupId"]].append(r)
    out = {}
    for gid, grp in by_group.items():
        if gid == 0:
            for r in grp:
                if r["Chance"] > 0:
                    out[r["Item"]] = out.get(r["Item"], 0) + r["Chance"]
            continue
        explicit = sum(r["Chance"] for r in grp if r["Chance"] > 0)
        zeros = [r for r in grp if r["Chance"] <= 0]
        for r in grp:
            if r["Chance"] > 0:
                out[r["Item"]] = out.get(r["Item"], 0) + r["Chance"]
        if zeros and explicit < 100:
            share = (100.0 - explicit) / len(zeros)
            for r in zeros:
                out[r["Item"]] = out.get(r["Item"], 0) + share
    return {i: min(p, 100.0) for i, p in out.items()}


def fmt(p):
    p = round(p, 2)
    return ("%g" % p)


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def main(world_sql, addons_dir):
    loot = collections.defaultdict(list)
    for r in t.rows(world_sql, "creature_loot_template",
                    ["Entry", "ItemType", "Item", "Chance", "GroupId", "LootMode"]):
        if r["ItemType"] == ITEM and (r["LootMode"] or 1) & 1:
            loot[r["Entry"]].append(r)

    resolved = {lid: group_chances(rows) for lid, rows in loot.items()}

    # One loot id per NPC: the base (difficulty 0) table when there is one, otherwise
    # the lowest difficulty that has loot.
    pick = {}
    for r in t.rows(world_sql, "creature_template_difficulty", ["Entry", "DifficultyID", "LootID"]):
        lid = r["LootID"]
        if not lid or not resolved.get(lid):
            continue
        cur = pick.get(r["Entry"])
        if cur is None or r["DifficultyID"] < cur[0]:
            pick[r["Entry"]] = (r["DifficultyID"], lid)

    names = {r["entry"]: r["name"] for r in t.rows(world_sql, "creature_template", ["entry", "name"])}

    out_dir = os.path.join(addons_dir, "WhatItDrops_Retail")
    os.makedirs(out_dir, exist_ok=True)
    skipped_big, written, rows_total = [], 0, 0
    lines = [
        "-- AUTO-GENERATED by tools/generate-retail-from-tdb.py -- do not edit.",
        "-- Retail creature loot from the TrinityCore TDB world database (GPL v3).",
        "-- Flat: d[npc]={specificCount,item,pct,...}, rate-sorted. Item names come from the client.",
        "WhatItDropsFull = WhatItDropsFull or {}",
        "WhatItDropsNpcName = WhatItDropsNpcName or {}",
        "local d, n = WhatItDropsFull, WhatItDropsNpcName",
        "",
    ]
    for npc in sorted(pick):
        items = sorted(resolved[pick[npc][1]].items(), key=lambda kv: -kv[1])
        if len(items) > MAX_ROWS:
            skipped_big.append((npc, names.get(npc), len(items)))
            continue
        flat = ",".join("%d,%s" % (i, fmt(p)) for i, p in items)
        lines.append("d[%d]={%d,%s}" % (npc, len(items), flat))
        nm = names.get(npc)
        if nm:
            lines.append("n[%d]=%s" % (npc, lua_str(nm)))
        written += 1
        rows_total += len(items)

    with open(os.path.join(out_dir, "WhatItDrops_Retail.lua"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(out_dir, "WhatItDrops_Retail.toc"), "w", encoding="utf-8", newline="\n") as f:
        f.write("## Interface: 16001, 20505, 120100\n"
                "## Title: WhatItDrops |cff66ccffRetail Data|r\n"
                "## Notes: Retail creature loot from the TrinityCore TDB (GPLv3). Loaded on demand by WhatItDrops.\n"
                "## Version: 1.2.0\n"
                "## LoadOnDemand: 1\n"
                "\n"
                "WhatItDrops_Retail.lua\n")
    size = os.path.getsize(os.path.join(out_dir, "WhatItDrops_Retail.lua"))
    print("NPCs written: %d   item rows: %d   file: %.1f MB" % (written, rows_total, size / 1048576))
    if skipped_big:
        print("skipped (over %d rows): %s" % (MAX_ROWS, skipped_big[:10]))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
